name: Migrate PR  

on:
  push:
    branches:
      - each.value
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Hello World
        run: echo "Hello World"

